# 既存の出力ファイルを上書きするかどうか (true/false)
# false の場合はファイル名に年月日時分秒のSuffixが付与されます
overwrite: false

# 1ファイルあたりの最大サイズ (MB) (既定: 95.0)
# このサイズを超えそうな場合、ファイルが分割されます
max_mb: 95.0

# 実行全体で処理する合計サイズの上限 (MB) (既定: 950.0)
# このサイズに達した時点で、スキャンを停止します
stop_threshold_mb: 950.0

ignore_patterns:
  - ".pytest_cache/*"
  - "test_output.md"
  - "【Repo】 *.md"
